# Docker Compose file for production environment
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: base-api
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:5
    container_name: mongo-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
